### ISSUE TITLE
Source of *typotests-doc.pdf*

### ISSUE THREAD

**Issue by aksr** [reffort/typo-tests-documents#1]
I would like to take a look at the source of *typotests-doc.pdf*.
Any chance for it to be released?

**Comment by reffort** [comment]
typotests-doc was done with some experimental macros that are presently rather incomplete.  I didn't include the source for that reason (without the macros and related files, you can't build the document from the source).

I would be happy to address any questions you have about it.  There isn't really anything that can't be done with -ms and a few simple macros, other than the margin notes.

**Comment by aksr** [comment]
If it's not a problem and if you are comfortable with it, I would still like to take a look at it.

**Comment by reffort** [comment]
I added a few sample files to show how the document is marked up.  This document was intended as an "out of sample" test for the macros, so if the complete source is released, I'll probably convert it to a self-contained form.  There's also the grap source for one of the figures.
